POST http://192.168.0.21:3002/convert
Content-Type: application/json

{
    "convertParams": {
        "url": "https://www.youtube.com/shorts/Os2tfilLj8c",
        "type": "video"
    }
}

###

GET http://192.168.0.21:3002/info?url=https://www.youtube.com/shorts/Os2tfilLj8c

### 

GET http://192.168.0.21:3002/download/1774378507749?type=video


###